version: "3.8"

services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,apigateway,dynamodb,sqs,sns,cloudwatch,cloudformation,ssm,s3,iam,logs
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"